Django/salessite/products/urls.py
from django.urls import path
from . views import Homepage
from cart.views import add_product, CartView
app_name= 'products'

urlpatterns = [
    path('', Homepage.as_view(), name='home'),
    path('cart/', CartView, name='cart-home'),
    path('cart/<slug>', add_product, name='cart'),
]

Django/salessite/salessite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls',namespace='products')),
]

Django/salessite/cart/models.py
from django.db import models
from django.contrib.auth import get_user_model
from products.models import Product as m_product
# Create your models here.

m_user = get_user_model()

class Cart(models.Model):
    user = models.ForeignKey(m_user, on_delete = models.PROTECT)
    product = models.ForeignKey(m_product, on_delete = models.PROTECT)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return self.user.username

    def sum(self):
        return self.product.price * self.quantity


class Order(models.Model):
    user = models.ForeignKey(m_user, on_delete = models.PROTECT)
    items = models.ManyToManyField(Cart)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def sum(self):
        return sum(item.sum() for item in self.items.all())

Django/salessite/products/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length = 100)
    desc = models.TextField(max_length = 500)
    price = models.FloatField()
    img = models.CharField(max_length = 50)
    category = models.ForeignKey(Category, on_delete = models.PROTECT)
    slug = models.SlugField()

    def __str__(self):
        return self.name

Django/salessite/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from .models import Cart, Order
from products.models import Product
# Create your views here.

def add_product(request, slug):
    product_object = get_object_or_404(Product, slug=slug)
    current_item, created = Cart.objects.get_or_create(
        product=product_object
    )
    order_queue = Order.objects.filter(ordered=False)
    if order_queue.exists():
        current_order = order_queue[0]
        if current_order.items.filter(product__slug=product_object.slug).exists():
            current_item.quantity += 1
            current_item.save()
            return redirect("products:home")
        else:
            current_order.items.add(current_item)
            return redirect("products:home")
    else:
        current_order = Order.objects.create()
        current_order.items.add(current_item)
        return redirect("products:home")

def CartView(request):
    carts = Cart.objects.all()
    orders = Order.objects.filter(ordered = False)

    if carts.exists():
        order = orders[0]
        return render(request, 'cart/index.html', {"carts": carts, 'order': order})
    else:
        return redirect("products:home")

Django/salessite/products/views.py
from django.shortcuts import render
from django.views.generic import ListView
from products.models import Product

# Create your views here.
class Homepage(ListView):
    model = Product
    template_name = 'products/index.html'

Django/salessite/cart/templates/cart/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Dogs, Inc.</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light list-unstyled">
        <a class="navbar-brand" href="{% url 'products:home' %}">Dogs, Inc.</a>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'products:home' %}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" href="{% url 'products:cart-home' %}">Cart</a>
        </li>
    </nav>
    <div class="container">
        <h2>Your Cart</h2>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Product</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Price</th>
                </tr>
            </thead>
            <tbody>
                {% for cart in carts %}
                <tr>
                    <td>
                        {{ cart.product.name }}
                    </td>
                    <td>
                        {{ cart.quantity }}
                    </td>
                    <td>
                        €{{ cart.sum | floatformat:2 }}
                    </td>
                </tr>
                {% endfor %}
                <tr>
                    <th scope="row"></th>
                    <td colspan="1">Total</td>
                    <td>€{{ order.sum | floatformat:2 }}</td>
                </tr>
                <tr>
                    <th scope="row"></th>
                    <td colspan="3" class="text-right ">
                        <a href="{% url 'products:home' %}" class="btn btn-outline-dark">Home</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</body>

Django/salessite/products/templates/products/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <title>Dogs, Inc.</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light list-unstyled">
        <a class="navbar-brand" href="{% url 'products:home' %}">Dogs, Inc.</a>
        <li class="nav-item active">
            <a class="nav-link disabled" href="{% url 'products:home' %}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'products:cart-home' %}">Cart</a>
        </li>
    </nav>
    <div class="container">
        <div class="row">
            {% for product in object_list %}
            <div class="col-md-4 col-lg-4 col-sm-3 col-xs-1">
                <div class="card mb-3" style="max-width: 540px;">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                            <img src="{% get_static_prefix %}{{product.img}}" style="width:100%;">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">{{product.name}}</h5>
                                <p class="card-text">{{product.desc}}</p>
                                <p class="card-text"><small class="text-muted">€{{product.price}}</small></p>
                            </div>
                            <div class='card-footer text-center'>
                                <a href="cart/{{product.slug}}" class="btn btn-outline-dark">Add to Cart</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</body>

</html>